/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 beacon.glb 
*/

import React from 'react'
import { useMemo, useRef, useLayoutEffect } from 'react';
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";
import * as THREE from 'three'
import { createTimeline } from 'animejs'

const BeaconModel = ({ scrollProgressRef, baseScale = 4, glow = true, ...props }) => {
  const { nodes, materials } = useGLTF('./models/beacon.glb')
  const ref = useRef();
  const batteriesRef = useRef();
  const chipsRef1 = useRef();
  const chipsRef2 = useRef();
  const pcbRef = useRef();
  const timelineRef = useRef(null)
  const opacityStateRef = useRef({ value: 1 })

  const texture = useMemo(() => {
    const loader = new THREE.TextureLoader()
    const t = loader.load('./noise.jpg')
    t.wrapS = THREE.RepeatWrapping
    t.wrapT = THREE.RepeatWrapping
    return t
  }, [])

  const anodisedMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      color: 0xff9a42,
      roughness: 0.4,
      metalness: 0.8,
      roughnessMap: texture,
      metalnessMap: texture,
      opacity: 1,
      transparent: true,
      envMapIntensity: 0.9,
    })
  }, [texture])

  const engravingGlowMaterial = useMemo(() => {
    const mat = new THREE.MeshStandardMaterial({
      // Slightly "hotter" version of the anodised enclosure
      color: 0x000000,
      emissive: new THREE.Color(0x000000),
      emissiveIntensity: 3.25,
      emissiveMap: texture,
      roughness: 0.02,
      metalness: 1.9,
      // roughnessMap: texture,
      // metalnessMap: texture,
      // bumpMap: texture,
      // bumpScale: 0.03,
      // envMapIntensity: 1.15,
      clearcoat: 0.35,
      clearcoatRoughness: 0.22,
      transparent: true,
      opacity: 0.92,
    })
    return mat
  }, [texture])

  const pcbMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      color: 0x008800,
      roughness: 0.95,
      metalness: 0.02,
      roughnessMap: texture,
      envMapIntensity: 1,
    })
  }, [texture])

  const insulatorMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      color: 0x666666,
      roughness: 0.6,
      metalness: 0.1,
      roughnessMap: texture,
      metalnessMap: texture,
      envMapIntensity: 1,
    })
  }, [texture])

  const batteryMaterial = useMemo(() => {
    return new THREE.MeshStandardMaterial({
      color: 0x049ef4,
      roughness: 0.1,
      metalness: 0.2,
    })
  }, [])

  useFrame(() => {
    const timeline = timelineRef.current
    if (timeline) {
      const progress = scrollProgressRef?.current ?? 0
      timeline.seek(progress * timeline.duration)
    }

    anodisedMaterial.opacity = opacityStateRef.current.value
  })

  useLayoutEffect(() => {
    if (!ref.current) return

    const tl = createTimeline({ autoplay: false, easing: 'easeInOutQuad' })

    // Enable shadows on all meshes for a more realistic product render.
    ref.current.traverse((obj) => {
      if (!obj) return
      if (obj.isMesh) {
        obj.castShadow = true
        obj.receiveShadow = true
      }
    })

    // Page 1: keep the model framed on the right, with a gentle rotation.
    tl.add(
      {
        targets: ref.current.rotation,
        duration: 1200,
        x: ref.current.rotation.x + Math.PI / 10,
        y: ref.current.rotation.y + Math.PI * 0.8,
        z: ref.current.rotation.z,
      },
      0,
    )

    tl.add(
      {
        targets: ref.current.scale,
        duration: 1200,
        x: baseScale,
        y: baseScale,
        z: baseScale,
      },
      0,
    )

    // Transition into page 2: drift slightly left and forward
    tl.add(
      {
        targets: ref.current.position,
        duration: 900,
        x: -2.2,
        y: -0.6,
        z: 1.2,
      },
      900,
    )

    // Explode internals
    if (batteriesRef.current) {
      tl.add(
        {
          targets: batteriesRef.current.position,
          duration: 1000,
          y: 2,
          z: 4,
        },
        1050,
      )
    }

    if (pcbRef.current) {
      tl.add(
        {
          targets: pcbRef.current.position,
          duration: 1000,
          y: 4,
          z: -2,
        },
        1000,
      )
    }

    if (chipsRef1.current) {
      tl.add(
        {
          targets: chipsRef1.current.position,
          duration: 1000,
          y: 8,
          x: -2,
          z: -2,
        },
        1000,
      )
    }

    if (chipsRef2.current) {
      tl.add(
        {
          targets: chipsRef2.current.position,
          duration: 1000,
          y: 8,
        },
        1050,
      )
    }

    // Fade the enclosure as we approach page 2
    tl.add(
      {
        targets: opacityStateRef.current,
        duration: 900,
        value: 0.2,
      },
      850,
    )

    timelineRef.current = tl
  }, [baseScale]);

  // console.log(materials['Aluminum_-_Bead_Blasted.001'])

  return (
    <group {...props} dispose={null}>
      <group
        rotation={[Math.PI / 2, Math.PI, 0]}
        scale={[baseScale, baseScale, baseScale]}
        ref={ref}
      >

        {/* Internal lighting (glows through openings) */}
        {glow && (
          <group>
            <group position={[0.0, 0.6, 1.4]}>
              <pointLight
                color="#FFE6C9"
                intensity={0.12}
                distance={2.2}
                decay={2}
              />
              <mesh>
                <sphereGeometry args={[0.05, 14, 14]} />
                <meshBasicMaterial color="#FFE6C9" toneMapped={false} transparent opacity={0.35} />
              </mesh>
            </group>

            {/* <group position={[1, 1, 1]}>
              <pointLight
                color="#FFCA16"
                intensity={0.8}
                distance={0}
                decay={0.2}
              />
              <mesh>
                <sphereGeometry args={[0.11, 18, 18]} />
                <meshBasicMaterial color="#FFCA16" toneMapped={false} />
              </mesh>
            </group> */}
          </group>
        )}
        
        {/* Enclosure */}
        <group>
          <group>
            <mesh position={[0, 2.42, 3.1]}>
              <boxGeometry args={[5.4, 0.1, 0.86]} />
              <primitive object={engravingGlowMaterial} attach="material" />
            </mesh>
          </group>
          <mesh geometry={nodes['Beacon-model_1'].geometry} material={anodisedMaterial} />
        </group>

        {/* Batteries */}
        <group position={[0,0,0]}>
          <group ref={batteriesRef}>
            <mesh geometry={nodes['Beacon-model_2'].geometry} material={batteryMaterial} />
          </group>
        </group>

        {/* chip (yet to identify) */}
        <group position={[0,0,0]}>
          <group ref={chipsRef1}>
            {/* Iridium */}
            <mesh geometry={nodes['Beacon-model_18'].geometry} material={materials['Opaque(144,144,144)']} />
          </group>
        </group>
        <group position={[0,0,0]}>
          <group ref={chipsRef2}>
            {/* IMU */}
            <mesh geometry={nodes['Beacon-model_6'].geometry} material={materials['Opaque(128,128,128)']} />
          </group>
        </group>
        

        

        {/* Chip (yet to identify) */}
        <group position={[0,0,0]}>
          <group ref={pcbRef}>
            {/* PCB + P/C 104 */}
            <mesh geometry={nodes['Beacon-model_3'].geometry} material={insulatorMaterial} />
            <mesh geometry={nodes['Beacon-model_5'].geometry} material={pcbMaterial} />
            
            {/* Harwin green connector */}
            <mesh geometry={nodes['Beacon-model_7'].geometry} material={materials['Opaque(133,237,168)']} />
            <mesh geometry={nodes['Beacon-model_8'].geometry} material={materials['Opaque(168,168,168)']} />
            <mesh geometry={nodes['Beacon-model_9'].geometry} material={materials['Opaque(255,206,117)']} />
            
            {/* Coaxial connectors */}
            <mesh geometry={nodes['Beacon-model_10'].geometry} material={materials['Opaque(66,66,66)']} />
            <mesh geometry={nodes['Beacon-model_13'].geometry} material={materials['Opaque(236,236,236)']} />
          </group>
        </group>
        
        
        
      </group>
    </group>
  )
}


useGLTF.preload('./models/beacon.glb');

export { BeaconModel };